name: agent
services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - web_images:/assets/images
    depends_on:
      - adk

  adk:
    image: us-central1-docker.pkg.dev/jmahood-demo/adk:latest
    ports:
      - "3000:3000"
    models:
      - ai-model

models:
 ai-model:
    model: ai/gemma3-qat:4B-Q4_K_M
    x-google-cloudrun:
      inference-endpoint: docker/model-runner:latest-cuda12.2.2

volumes:
  web_images:
