version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  redis:
    image: redis:alpine
  web:
    build: .
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: vendor/bundle # Add this line
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - css # Add dependency on css service
  css: # New CSS service
    build: .
    environment:
      BUNDLE_PATH: vendor/bundle # Add this line
    command: bundle exec bin/rails tailwindcss:watch
    volumes:
      - .:/app

volumes:
  db_data: