
# Shows targets
list:
  just -l

# docker compose UP, logging to log/
dev:
  docker compose up 2>&1 | tee -a log/docker-compose-up.log
up: dev

app-initialize:
  echo run this AFTER up..
  just db-create db-migrate db-seed assets-precompile

# runs "rails console" - requires WEB to be up
console:
  docker compose exec web rails console

db-create:
  docker compose exec web rails db:create

# migrates the WEB app.
db-migrate:
  docker compose exec web rails db:migrate

# seeds the WEB app with sample data
db-seed:
  docker compose exec web rails db:seed

assets-precompile:
  docker compose exec web rails assets:precompile

test:
  docker compose exec web rails test

lint:
  docker compose exec web bundle exec rubocop

build:
  docker compose build

gemini-feedbackloop-build:
  timeout 60 docker compose build

force-rebuild:
  echo 'Note: this command can take up to 30 plus minutes.'
  date | tee -a log/docker-compose-build-nocache.log
  time docker compose build --no-cache 2>&1 | tee -a log/docker-compose-build-nocache.log

down:
  docker compose down -v

# Shows docker compose logs
logs:
  docker compose logs

