
# Shows targets
list:
  just -l

# docker compose UP
dev:
  docker compose up
up: dev

# runs "rails console" - requires WEB to be up
console:
  docker compose exec web rails console

db-create:
  docker compose exec web rails db:create

# migrates the WEB app.
db-migrate:
  docker compose exec web rails db:migrate

# seeds the WEB app with sample data
db-seed:
  docker compose exec web rails db:seed

test:
  docker compose exec web rails test

lint:
  docker compose exec web bundle exec rubocop

build:
  docker compose build

force-rebuild:
  docker compose build --no-cache

down:
  docker compose down -v

# Shows docker compose logs
logs:
  docker compose logs
