dev:
  docker compose up

console:
  docker compose exec web rails console

db-create:
  docker compose exec web rails db:create

db-migrate:
  docker compose exec web rails db:migrate

db-seed:
  docker compose exec web rails db:seed

test:
  docker compose exec web rails test

lint:
  docker compose exec web bundle exec rubocop

build:
  docker compose build

down:
  docker compose down -v
